### ISSUE TITLE
[PROPOSAL] Change Maven groupId

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/spring-data-opensearch#14]
The groupId is currently set to `org.opensearch` which is the top-level for OpenSearch. I suggest we have a sub-groupId. I'd probably recommend `org.opensearch.client` to have it sit with other Java clients. But, perhaps `org.opensearch.spring` is appropriate.

**Comment by rursprung** [comment]
i think `org.opensearch.client` instead of `org.opensearch.spring` might be better to have it aligned with the other clients. i think most OpenSearch artifacts are under some sub-group (e.g. `org.opensearch.plugins` for the project-owned plugins), so having it directly in `org.opensearch` would be wrong.

maybe it'd also be helpful to create a ticket in a central repository (the .github repo?) to document the maven groups used by the project / the pattern to be used for creating new maven groups? that shouldn't block this one here from moving ahead though, it'd just help as a guideline in the future.

**Comment by reta** [comment]
Closed as part of https://github.com/opensearch-project/spring-data-opensearch/pull/37

**Comment by reta** [comment]
The group is set to `org.opensearch.client`
